package main.java.com.tanklab.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DemandsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public DemandsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustomerNmIsNull() {
            addCriterion("customer_nm is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNmIsNotNull() {
            addCriterion("customer_nm is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNmEqualTo(String value) {
            addCriterion("customer_nm =", value, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmNotEqualTo(String value) {
            addCriterion("customer_nm <>", value, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmGreaterThan(String value) {
            addCriterion("customer_nm >", value, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmGreaterThanOrEqualTo(String value) {
            addCriterion("customer_nm >=", value, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmLessThan(String value) {
            addCriterion("customer_nm <", value, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmLessThanOrEqualTo(String value) {
            addCriterion("customer_nm <=", value, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmLike(String value) {
            addCriterion("customer_nm like", value, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmNotLike(String value) {
            addCriterion("customer_nm not like", value, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmIn(List<String> values) {
            addCriterion("customer_nm in", values, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmNotIn(List<String> values) {
            addCriterion("customer_nm not in", values, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmBetween(String value1, String value2) {
            addCriterion("customer_nm between", value1, value2, "customerNm");
            return (Criteria) this;
        }

        public Criteria andCustomerNmNotBetween(String value1, String value2) {
            addCriterion("customer_nm not between", value1, value2, "customerNm");
            return (Criteria) this;
        }

        public Criteria andIpSrcIsNull() {
            addCriterion("ip_src is null");
            return (Criteria) this;
        }

        public Criteria andIpSrcIsNotNull() {
            addCriterion("ip_src is not null");
            return (Criteria) this;
        }

        public Criteria andIpSrcEqualTo(String value) {
            addCriterion("ip_src =", value, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcNotEqualTo(String value) {
            addCriterion("ip_src <>", value, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcGreaterThan(String value) {
            addCriterion("ip_src >", value, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcGreaterThanOrEqualTo(String value) {
            addCriterion("ip_src >=", value, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcLessThan(String value) {
            addCriterion("ip_src <", value, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcLessThanOrEqualTo(String value) {
            addCriterion("ip_src <=", value, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcLike(String value) {
            addCriterion("ip_src like", value, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcNotLike(String value) {
            addCriterion("ip_src not like", value, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcIn(List<String> values) {
            addCriterion("ip_src in", values, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcNotIn(List<String> values) {
            addCriterion("ip_src not in", values, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcBetween(String value1, String value2) {
            addCriterion("ip_src between", value1, value2, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpSrcNotBetween(String value1, String value2) {
            addCriterion("ip_src not between", value1, value2, "ipSrc");
            return (Criteria) this;
        }

        public Criteria andIpDstIsNull() {
            addCriterion("ip_dst is null");
            return (Criteria) this;
        }

        public Criteria andIpDstIsNotNull() {
            addCriterion("ip_dst is not null");
            return (Criteria) this;
        }

        public Criteria andIpDstEqualTo(String value) {
            addCriterion("ip_dst =", value, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstNotEqualTo(String value) {
            addCriterion("ip_dst <>", value, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstGreaterThan(String value) {
            addCriterion("ip_dst >", value, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstGreaterThanOrEqualTo(String value) {
            addCriterion("ip_dst >=", value, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstLessThan(String value) {
            addCriterion("ip_dst <", value, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstLessThanOrEqualTo(String value) {
            addCriterion("ip_dst <=", value, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstLike(String value) {
            addCriterion("ip_dst like", value, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstNotLike(String value) {
            addCriterion("ip_dst not like", value, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstIn(List<String> values) {
            addCriterion("ip_dst in", values, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstNotIn(List<String> values) {
            addCriterion("ip_dst not in", values, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstBetween(String value1, String value2) {
            addCriterion("ip_dst between", value1, value2, "ipDst");
            return (Criteria) this;
        }

        public Criteria andIpDstNotBetween(String value1, String value2) {
            addCriterion("ip_dst not between", value1, value2, "ipDst");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("starttime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("starttime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("starttime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("starttime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("starttime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("starttime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("starttime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("starttime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("starttime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("starttime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("starttime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("starttime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endtime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endtime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endtime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endtime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endtime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endtime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andBandwidthIsNull() {
            addCriterion("bandwidth is null");
            return (Criteria) this;
        }

        public Criteria andBandwidthIsNotNull() {
            addCriterion("bandwidth is not null");
            return (Criteria) this;
        }

        public Criteria andBandwidthEqualTo(Integer value) {
            addCriterion("bandwidth =", value, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthNotEqualTo(Integer value) {
            addCriterion("bandwidth <>", value, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthGreaterThan(Integer value) {
            addCriterion("bandwidth >", value, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("bandwidth >=", value, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthLessThan(Integer value) {
            addCriterion("bandwidth <", value, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthLessThanOrEqualTo(Integer value) {
            addCriterion("bandwidth <=", value, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthIn(List<Integer> values) {
            addCriterion("bandwidth in", values, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthNotIn(List<Integer> values) {
            addCriterion("bandwidth not in", values, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthBetween(Integer value1, Integer value2) {
            addCriterion("bandwidth between", value1, value2, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andBandwidthNotBetween(Integer value1, Integer value2) {
            addCriterion("bandwidth not between", value1, value2, "bandwidth");
            return (Criteria) this;
        }

        public Criteria andLatencyIsNull() {
            addCriterion("latency is null");
            return (Criteria) this;
        }

        public Criteria andLatencyIsNotNull() {
            addCriterion("latency is not null");
            return (Criteria) this;
        }

        public Criteria andLatencyEqualTo(Integer value) {
            addCriterion("latency =", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyNotEqualTo(Integer value) {
            addCriterion("latency <>", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyGreaterThan(Integer value) {
            addCriterion("latency >", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyGreaterThanOrEqualTo(Integer value) {
            addCriterion("latency >=", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyLessThan(Integer value) {
            addCriterion("latency <", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyLessThanOrEqualTo(Integer value) {
            addCriterion("latency <=", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyIn(List<Integer> values) {
            addCriterion("latency in", values, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyNotIn(List<Integer> values) {
            addCriterion("latency not in", values, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyBetween(Integer value1, Integer value2) {
            addCriterion("latency between", value1, value2, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyNotBetween(Integer value1, Integer value2) {
            addCriterion("latency not between", value1, value2, "latency");
            return (Criteria) this;
        }

        public Criteria andLossIsNull() {
            addCriterion("loss is null");
            return (Criteria) this;
        }

        public Criteria andLossIsNotNull() {
            addCriterion("loss is not null");
            return (Criteria) this;
        }

        public Criteria andLossEqualTo(Integer value) {
            addCriterion("loss =", value, "loss");
            return (Criteria) this;
        }

        public Criteria andLossNotEqualTo(Integer value) {
            addCriterion("loss <>", value, "loss");
            return (Criteria) this;
        }

        public Criteria andLossGreaterThan(Integer value) {
            addCriterion("loss >", value, "loss");
            return (Criteria) this;
        }

        public Criteria andLossGreaterThanOrEqualTo(Integer value) {
            addCriterion("loss >=", value, "loss");
            return (Criteria) this;
        }

        public Criteria andLossLessThan(Integer value) {
            addCriterion("loss <", value, "loss");
            return (Criteria) this;
        }

        public Criteria andLossLessThanOrEqualTo(Integer value) {
            addCriterion("loss <=", value, "loss");
            return (Criteria) this;
        }

        public Criteria andLossIn(List<Integer> values) {
            addCriterion("loss in", values, "loss");
            return (Criteria) this;
        }

        public Criteria andLossNotIn(List<Integer> values) {
            addCriterion("loss not in", values, "loss");
            return (Criteria) this;
        }

        public Criteria andLossBetween(Integer value1, Integer value2) {
            addCriterion("loss between", value1, value2, "loss");
            return (Criteria) this;
        }

        public Criteria andLossNotBetween(Integer value1, Integer value2) {
            addCriterion("loss not between", value1, value2, "loss");
            return (Criteria) this;
        }

        public Criteria andStatisfyIsNull() {
            addCriterion("statisfy is null");
            return (Criteria) this;
        }

        public Criteria andStatisfyIsNotNull() {
            addCriterion("statisfy is not null");
            return (Criteria) this;
        }

        public Criteria andStatisfyEqualTo(String value) {
            addCriterion("statisfy =", value, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyNotEqualTo(String value) {
            addCriterion("statisfy <>", value, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyGreaterThan(String value) {
            addCriterion("statisfy >", value, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyGreaterThanOrEqualTo(String value) {
            addCriterion("statisfy >=", value, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyLessThan(String value) {
            addCriterion("statisfy <", value, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyLessThanOrEqualTo(String value) {
            addCriterion("statisfy <=", value, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyLike(String value) {
            addCriterion("statisfy like", value, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyNotLike(String value) {
            addCriterion("statisfy not like", value, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyIn(List<String> values) {
            addCriterion("statisfy in", values, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyNotIn(List<String> values) {
            addCriterion("statisfy not in", values, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyBetween(String value1, String value2) {
            addCriterion("statisfy between", value1, value2, "statisfy");
            return (Criteria) this;
        }

        public Criteria andStatisfyNotBetween(String value1, String value2) {
            addCriterion("statisfy not between", value1, value2, "statisfy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table demands
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 22 20:50:33 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table demands
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}