package main.java.com.tanklab.entity;

public class Flowtable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flowtable.id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flowtable.belong_sw_id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    private String belongSwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flowtable.table_id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    private String tableId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flowtable.id
     *
     * @return the value of flowtable.id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flowtable.id
     *
     * @param id the value for flowtable.id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flowtable.belong_sw_id
     *
     * @return the value of flowtable.belong_sw_id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    public String getBelongSwId() {
        return belongSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flowtable.belong_sw_id
     *
     * @param belongSwId the value for flowtable.belong_sw_id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    public void setBelongSwId(String belongSwId) {
        this.belongSwId = belongSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flowtable.table_id
     *
     * @return the value of flowtable.table_id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flowtable.table_id
     *
     * @param tableId the value for flowtable.table_id
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }
}