package main.java.com.tanklab.entity;

public class Host {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.type
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String hostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.mac_addr
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String macAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.ipv4_addr
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String ipv4Addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.con_sw_port_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String conSwPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.state
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.id
     *
     * @return the value of host.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.id
     *
     * @param id the value for host.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.type
     *
     * @return the value of host.type
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.type
     *
     * @param type the value for host.type
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_id
     *
     * @return the value of host.host_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_id
     *
     * @param hostId the value for host.host_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setHostId(String hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.mac_addr
     *
     * @return the value of host.mac_addr
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getMacAddr() {
        return macAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.mac_addr
     *
     * @param macAddr the value for host.mac_addr
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setMacAddr(String macAddr) {
        this.macAddr = macAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.ipv4_addr
     *
     * @return the value of host.ipv4_addr
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getIpv4Addr() {
        return ipv4Addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.ipv4_addr
     *
     * @param ipv4Addr the value for host.ipv4_addr
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setIpv4Addr(String ipv4Addr) {
        this.ipv4Addr = ipv4Addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.con_sw_port_id
     *
     * @return the value of host.con_sw_port_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getConSwPortId() {
        return conSwPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.con_sw_port_id
     *
     * @param conSwPortId the value for host.con_sw_port_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setConSwPortId(String conSwPortId) {
        this.conSwPortId = conSwPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.state
     *
     * @return the value of host.state
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.state
     *
     * @param state the value for host.state
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }
}