package main.java.com.tanklab.entity;

public class Host {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String hostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String topologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_tracker_service_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String hostTrackerServiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_tracker_service_addresses
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String hostTrackerServiceAddresses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_tracker_service_attachment_points
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String hostTrackerServiceAttachmentPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.termination-point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String terminationPoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.id
     *
     * @return the value of host.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.id
     *
     * @param id the value for host.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.type
     *
     * @return the value of host.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.type
     *
     * @param type the value for host.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_id
     *
     * @return the value of host.host_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_id
     *
     * @param hostId the value for host.host_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setHostId(String hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.state
     *
     * @return the value of host.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.state
     *
     * @param state the value for host.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.topology_id
     *
     * @return the value of host.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTopologyId() {
        return topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.topology_id
     *
     * @param topologyId the value for host.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTopologyId(String topologyId) {
        this.topologyId = topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_tracker_service_id
     *
     * @return the value of host.host_tracker_service_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getHostTrackerServiceId() {
        return hostTrackerServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_tracker_service_id
     *
     * @param hostTrackerServiceId the value for host.host_tracker_service_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setHostTrackerServiceId(String hostTrackerServiceId) {
        this.hostTrackerServiceId = hostTrackerServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_tracker_service_addresses
     *
     * @return the value of host.host_tracker_service_addresses
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getHostTrackerServiceAddresses() {
        return hostTrackerServiceAddresses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_tracker_service_addresses
     *
     * @param hostTrackerServiceAddresses the value for host.host_tracker_service_addresses
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setHostTrackerServiceAddresses(String hostTrackerServiceAddresses) {
        this.hostTrackerServiceAddresses = hostTrackerServiceAddresses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_tracker_service_attachment_points
     *
     * @return the value of host.host_tracker_service_attachment_points
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getHostTrackerServiceAttachmentPoints() {
        return hostTrackerServiceAttachmentPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_tracker_service_attachment_points
     *
     * @param hostTrackerServiceAttachmentPoints the value for host.host_tracker_service_attachment_points
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setHostTrackerServiceAttachmentPoints(String hostTrackerServiceAttachmentPoints) {
        this.hostTrackerServiceAttachmentPoints = hostTrackerServiceAttachmentPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.termination-point
     *
     * @return the value of host.termination-point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTerminationPoint() {
        return terminationPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.termination-point
     *
     * @param terminationPoint the value for host.termination-point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTerminationPoint(String terminationPoint) {
        this.terminationPoint = terminationPoint;
    }
}