package main.java.com.tanklab.entity;

public class Link {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.src_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String srcSwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.dst_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String dstSwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.src_port_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String srcPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.dst_port_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String dstPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String topologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.bandwith
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer bandwith;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.latency
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer latency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.loss
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer loss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.id
     *
     * @return the value of link.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.id
     *
     * @param id the value for link.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_id
     *
     * @return the value of link.link_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_id
     *
     * @param linkId the value for link.link_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.src_sw_id
     *
     * @return the value of link.src_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getSrcSwId() {
        return srcSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.src_sw_id
     *
     * @param srcSwId the value for link.src_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setSrcSwId(String srcSwId) {
        this.srcSwId = srcSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.dst_sw_id
     *
     * @return the value of link.dst_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getDstSwId() {
        return dstSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.dst_sw_id
     *
     * @param dstSwId the value for link.dst_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setDstSwId(String dstSwId) {
        this.dstSwId = dstSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.src_port_id
     *
     * @return the value of link.src_port_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getSrcPortId() {
        return srcPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.src_port_id
     *
     * @param srcPortId the value for link.src_port_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setSrcPortId(String srcPortId) {
        this.srcPortId = srcPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.dst_port_id
     *
     * @return the value of link.dst_port_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getDstPortId() {
        return dstPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.dst_port_id
     *
     * @param dstPortId the value for link.dst_port_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setDstPortId(String dstPortId) {
        this.dstPortId = dstPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.topology_id
     *
     * @return the value of link.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTopologyId() {
        return topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.topology_id
     *
     * @param topologyId the value for link.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTopologyId(String topologyId) {
        this.topologyId = topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.bandwith
     *
     * @return the value of link.bandwith
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getBandwith() {
        return bandwith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.bandwith
     *
     * @param bandwith the value for link.bandwith
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setBandwith(Integer bandwith) {
        this.bandwith = bandwith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.latency
     *
     * @return the value of link.latency
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getLatency() {
        return latency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.latency
     *
     * @param latency the value for link.latency
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setLatency(Integer latency) {
        this.latency = latency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.loss
     *
     * @return the value of link.loss
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getLoss() {
        return loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.loss
     *
     * @param loss the value for link.loss
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setLoss(Integer loss) {
        this.loss = loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.state
     *
     * @return the value of link.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.state
     *
     * @param state the value for link.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }
}