package main.java.com.tanklab.entity;

import java.util.ArrayList;
import java.util.List;

public class NodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public NodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDatapathIdIsNull() {
            addCriterion("datapath_id is null");
            return (Criteria) this;
        }

        public Criteria andDatapathIdIsNotNull() {
            addCriterion("datapath_id is not null");
            return (Criteria) this;
        }

        public Criteria andDatapathIdEqualTo(String value) {
            addCriterion("datapath_id =", value, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdNotEqualTo(String value) {
            addCriterion("datapath_id <>", value, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdGreaterThan(String value) {
            addCriterion("datapath_id >", value, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdGreaterThanOrEqualTo(String value) {
            addCriterion("datapath_id >=", value, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdLessThan(String value) {
            addCriterion("datapath_id <", value, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdLessThanOrEqualTo(String value) {
            addCriterion("datapath_id <=", value, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdLike(String value) {
            addCriterion("datapath_id like", value, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdNotLike(String value) {
            addCriterion("datapath_id not like", value, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdIn(List<String> values) {
            addCriterion("datapath_id in", values, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdNotIn(List<String> values) {
            addCriterion("datapath_id not in", values, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdBetween(String value1, String value2) {
            addCriterion("datapath_id between", value1, value2, "datapathId");
            return (Criteria) this;
        }

        public Criteria andDatapathIdNotBetween(String value1, String value2) {
            addCriterion("datapath_id not between", value1, value2, "datapathId");
            return (Criteria) this;
        }

        public Criteria andSwithchnameIsNull() {
            addCriterion("swithchName is null");
            return (Criteria) this;
        }

        public Criteria andSwithchnameIsNotNull() {
            addCriterion("swithchName is not null");
            return (Criteria) this;
        }

        public Criteria andSwithchnameEqualTo(String value) {
            addCriterion("swithchName =", value, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameNotEqualTo(String value) {
            addCriterion("swithchName <>", value, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameGreaterThan(String value) {
            addCriterion("swithchName >", value, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameGreaterThanOrEqualTo(String value) {
            addCriterion("swithchName >=", value, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameLessThan(String value) {
            addCriterion("swithchName <", value, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameLessThanOrEqualTo(String value) {
            addCriterion("swithchName <=", value, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameLike(String value) {
            addCriterion("swithchName like", value, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameNotLike(String value) {
            addCriterion("swithchName not like", value, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameIn(List<String> values) {
            addCriterion("swithchName in", values, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameNotIn(List<String> values) {
            addCriterion("swithchName not in", values, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameBetween(String value1, String value2) {
            addCriterion("swithchName between", value1, value2, "swithchname");
            return (Criteria) this;
        }

        public Criteria andSwithchnameNotBetween(String value1, String value2) {
            addCriterion("swithchName not between", value1, value2, "swithchname");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefIsNull() {
            addCriterion("odlNodeRef is null");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefIsNotNull() {
            addCriterion("odlNodeRef is not null");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefEqualTo(String value) {
            addCriterion("odlNodeRef =", value, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefNotEqualTo(String value) {
            addCriterion("odlNodeRef <>", value, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefGreaterThan(String value) {
            addCriterion("odlNodeRef >", value, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefGreaterThanOrEqualTo(String value) {
            addCriterion("odlNodeRef >=", value, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefLessThan(String value) {
            addCriterion("odlNodeRef <", value, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefLessThanOrEqualTo(String value) {
            addCriterion("odlNodeRef <=", value, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefLike(String value) {
            addCriterion("odlNodeRef like", value, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefNotLike(String value) {
            addCriterion("odlNodeRef not like", value, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefIn(List<String> values) {
            addCriterion("odlNodeRef in", values, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefNotIn(List<String> values) {
            addCriterion("odlNodeRef not in", values, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefBetween(String value1, String value2) {
            addCriterion("odlNodeRef between", value1, value2, "odlnoderef");
            return (Criteria) this;
        }

        public Criteria andOdlnoderefNotBetween(String value1, String value2) {
            addCriterion("odlNodeRef not between", value1, value2, "odlnoderef");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table node
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 22 17:40:06 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}