package main.java.com.tanklab.entity;

public class Node {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.type
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.datapath_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String datapathId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.swithchName
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String swithchname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.odlNodeRef
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String odlnoderef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.state
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.id
     *
     * @return the value of node.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.id
     *
     * @param id the value for node.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.type
     *
     * @return the value of node.type
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.type
     *
     * @param type the value for node.type
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.datapath_id
     *
     * @return the value of node.datapath_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getDatapathId() {
        return datapathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.datapath_id
     *
     * @param datapathId the value for node.datapath_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setDatapathId(String datapathId) {
        this.datapathId = datapathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.swithchName
     *
     * @return the value of node.swithchName
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getSwithchname() {
        return swithchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.swithchName
     *
     * @param swithchname the value for node.swithchName
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setSwithchname(String swithchname) {
        this.swithchname = swithchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.odlNodeRef
     *
     * @return the value of node.odlNodeRef
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getOdlnoderef() {
        return odlnoderef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.odlNodeRef
     *
     * @param odlnoderef the value for node.odlNodeRef
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setOdlnoderef(String odlnoderef) {
        this.odlnoderef = odlnoderef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.state
     *
     * @return the value of node.state
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.state
     *
     * @param state the value for node.state
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }
}