package main.java.com.tanklab.entity;

public class OpenflowNode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_node.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_node.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_node.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String topologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_node.termination_point_names
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String terminationPointNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_node.opendaylight-topology-inventory_inventory-node-ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String opendaylightTopologyInventoryInventoryNodeRef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_node.id
     *
     * @return the value of openflow_node.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_node.id
     *
     * @param id the value for openflow_node.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_node.node_id
     *
     * @return the value of openflow_node.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_node.node_id
     *
     * @param nodeId the value for openflow_node.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_node.topology_id
     *
     * @return the value of openflow_node.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTopologyId() {
        return topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_node.topology_id
     *
     * @param topologyId the value for openflow_node.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTopologyId(String topologyId) {
        this.topologyId = topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_node.termination_point_names
     *
     * @return the value of openflow_node.termination_point_names
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTerminationPointNames() {
        return terminationPointNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_node.termination_point_names
     *
     * @param terminationPointNames the value for openflow_node.termination_point_names
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTerminationPointNames(String terminationPointNames) {
        this.terminationPointNames = terminationPointNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_node.opendaylight-topology-inventory_inventory-node-ref
     *
     * @return the value of openflow_node.opendaylight-topology-inventory_inventory-node-ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getOpendaylightTopologyInventoryInventoryNodeRef() {
        return opendaylightTopologyInventoryInventoryNodeRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_node.opendaylight-topology-inventory_inventory-node-ref
     *
     * @param opendaylightTopologyInventoryInventoryNodeRef the value for openflow_node.opendaylight-topology-inventory_inventory-node-ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setOpendaylightTopologyInventoryInventoryNodeRef(String opendaylightTopologyInventoryInventoryNodeRef) {
        this.opendaylightTopologyInventoryInventoryNodeRef = opendaylightTopologyInventoryInventoryNodeRef;
    }
}