package main.java.com.tanklab.entity;

public class OpenflowPoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_point.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_point.tp_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String tpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_point.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_point.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String topologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openflow_point.opendaylight_topology_inventory_inventory_node_connector_ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String opendaylightTopologyInventoryInventoryNodeConnectorRef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_point.id
     *
     * @return the value of openflow_point.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_point.id
     *
     * @param id the value for openflow_point.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_point.tp_id
     *
     * @return the value of openflow_point.tp_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_point.tp_id
     *
     * @param tpId the value for openflow_point.tp_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTpId(String tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_point.node_id
     *
     * @return the value of openflow_point.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_point.node_id
     *
     * @param nodeId the value for openflow_point.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_point.topology_id
     *
     * @return the value of openflow_point.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTopologyId() {
        return topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_point.topology_id
     *
     * @param topologyId the value for openflow_point.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTopologyId(String topologyId) {
        this.topologyId = topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openflow_point.opendaylight_topology_inventory_inventory_node_connector_ref
     *
     * @return the value of openflow_point.opendaylight_topology_inventory_inventory_node_connector_ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getOpendaylightTopologyInventoryInventoryNodeConnectorRef() {
        return opendaylightTopologyInventoryInventoryNodeConnectorRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openflow_point.opendaylight_topology_inventory_inventory_node_connector_ref
     *
     * @param opendaylightTopologyInventoryInventoryNodeConnectorRef the value for openflow_point.opendaylight_topology_inventory_inventory_node_connector_ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setOpendaylightTopologyInventoryInventoryNodeConnectorRef(String opendaylightTopologyInventoryInventoryNodeConnectorRef) {
        this.opendaylightTopologyInventoryInventoryNodeConnectorRef = opendaylightTopologyInventoryInventoryNodeConnectorRef;
    }
}