package main.java.com.tanklab.entity;

public class OvsdbNode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.bridge_name
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String bridgeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String topologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.fail_mode
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String failMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.bridge_openflow_node_ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String bridgeOpenflowNodeRef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.bridge_other_configs
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String bridgeOtherConfigs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.bridge_uuid
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String bridgeUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.datapath_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String datapathId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.datapath_type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String datapathType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.managed_by
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String managedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.controller_entry
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String controllerEntry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.termination_point_names
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String terminationPointNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.fabric_capable_device_supported_fabric
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String fabricCapableDeviceSupportedFabric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ovsdb_node.fabric_capable_device_capability-supported
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String fabricCapableDeviceCapabilitySupported;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.id
     *
     * @return the value of ovsdb_node.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.id
     *
     * @param id the value for ovsdb_node.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.node_id
     *
     * @return the value of ovsdb_node.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.node_id
     *
     * @param nodeId the value for ovsdb_node.node_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.bridge_name
     *
     * @return the value of ovsdb_node.bridge_name
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getBridgeName() {
        return bridgeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.bridge_name
     *
     * @param bridgeName the value for ovsdb_node.bridge_name
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setBridgeName(String bridgeName) {
        this.bridgeName = bridgeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.type
     *
     * @return the value of ovsdb_node.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.type
     *
     * @param type the value for ovsdb_node.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.state
     *
     * @return the value of ovsdb_node.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.state
     *
     * @param state the value for ovsdb_node.state
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.topology_id
     *
     * @return the value of ovsdb_node.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTopologyId() {
        return topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.topology_id
     *
     * @param topologyId the value for ovsdb_node.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTopologyId(String topologyId) {
        this.topologyId = topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.fail_mode
     *
     * @return the value of ovsdb_node.fail_mode
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getFailMode() {
        return failMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.fail_mode
     *
     * @param failMode the value for ovsdb_node.fail_mode
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setFailMode(String failMode) {
        this.failMode = failMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.bridge_openflow_node_ref
     *
     * @return the value of ovsdb_node.bridge_openflow_node_ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getBridgeOpenflowNodeRef() {
        return bridgeOpenflowNodeRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.bridge_openflow_node_ref
     *
     * @param bridgeOpenflowNodeRef the value for ovsdb_node.bridge_openflow_node_ref
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setBridgeOpenflowNodeRef(String bridgeOpenflowNodeRef) {
        this.bridgeOpenflowNodeRef = bridgeOpenflowNodeRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.bridge_other_configs
     *
     * @return the value of ovsdb_node.bridge_other_configs
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getBridgeOtherConfigs() {
        return bridgeOtherConfigs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.bridge_other_configs
     *
     * @param bridgeOtherConfigs the value for ovsdb_node.bridge_other_configs
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setBridgeOtherConfigs(String bridgeOtherConfigs) {
        this.bridgeOtherConfigs = bridgeOtherConfigs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.bridge_uuid
     *
     * @return the value of ovsdb_node.bridge_uuid
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getBridgeUuid() {
        return bridgeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.bridge_uuid
     *
     * @param bridgeUuid the value for ovsdb_node.bridge_uuid
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setBridgeUuid(String bridgeUuid) {
        this.bridgeUuid = bridgeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.datapath_id
     *
     * @return the value of ovsdb_node.datapath_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getDatapathId() {
        return datapathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.datapath_id
     *
     * @param datapathId the value for ovsdb_node.datapath_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setDatapathId(String datapathId) {
        this.datapathId = datapathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.datapath_type
     *
     * @return the value of ovsdb_node.datapath_type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getDatapathType() {
        return datapathType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.datapath_type
     *
     * @param datapathType the value for ovsdb_node.datapath_type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setDatapathType(String datapathType) {
        this.datapathType = datapathType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.managed_by
     *
     * @return the value of ovsdb_node.managed_by
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getManagedBy() {
        return managedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.managed_by
     *
     * @param managedBy the value for ovsdb_node.managed_by
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setManagedBy(String managedBy) {
        this.managedBy = managedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.controller_entry
     *
     * @return the value of ovsdb_node.controller_entry
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getControllerEntry() {
        return controllerEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.controller_entry
     *
     * @param controllerEntry the value for ovsdb_node.controller_entry
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setControllerEntry(String controllerEntry) {
        this.controllerEntry = controllerEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.termination_point_names
     *
     * @return the value of ovsdb_node.termination_point_names
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTerminationPointNames() {
        return terminationPointNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.termination_point_names
     *
     * @param terminationPointNames the value for ovsdb_node.termination_point_names
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTerminationPointNames(String terminationPointNames) {
        this.terminationPointNames = terminationPointNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.fabric_capable_device_supported_fabric
     *
     * @return the value of ovsdb_node.fabric_capable_device_supported_fabric
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getFabricCapableDeviceSupportedFabric() {
        return fabricCapableDeviceSupportedFabric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.fabric_capable_device_supported_fabric
     *
     * @param fabricCapableDeviceSupportedFabric the value for ovsdb_node.fabric_capable_device_supported_fabric
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setFabricCapableDeviceSupportedFabric(String fabricCapableDeviceSupportedFabric) {
        this.fabricCapableDeviceSupportedFabric = fabricCapableDeviceSupportedFabric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ovsdb_node.fabric_capable_device_capability-supported
     *
     * @return the value of ovsdb_node.fabric_capable_device_capability-supported
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getFabricCapableDeviceCapabilitySupported() {
        return fabricCapableDeviceCapabilitySupported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ovsdb_node.fabric_capable_device_capability-supported
     *
     * @param fabricCapableDeviceCapabilitySupported the value for ovsdb_node.fabric_capable_device_capability-supported
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setFabricCapableDeviceCapabilitySupported(String fabricCapableDeviceCapabilitySupported) {
        this.fabricCapableDeviceCapabilitySupported = fabricCapableDeviceCapabilitySupported;
    }
}