package main.java.com.tanklab.entity;

public class Qos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.belong_sw_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String belongSwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.qos_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String qosId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.qos_uuid
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String qosUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.qosBand
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    private String qosband;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.id
     *
     * @return the value of qos.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.id
     *
     * @param id the value for qos.id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.belong_sw_id
     *
     * @return the value of qos.belong_sw_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getBelongSwId() {
        return belongSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.belong_sw_id
     *
     * @param belongSwId the value for qos.belong_sw_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setBelongSwId(String belongSwId) {
        this.belongSwId = belongSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.qos_id
     *
     * @return the value of qos.qos_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getQosId() {
        return qosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.qos_id
     *
     * @param qosId the value for qos.qos_id
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setQosId(String qosId) {
        this.qosId = qosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.qos_uuid
     *
     * @return the value of qos.qos_uuid
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getQosUuid() {
        return qosUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.qos_uuid
     *
     * @param qosUuid the value for qos.qos_uuid
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setQosUuid(String qosUuid) {
        this.qosUuid = qosUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.qosBand
     *
     * @return the value of qos.qosBand
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public String getQosband() {
        return qosband;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.qosBand
     *
     * @param qosband the value for qos.qosBand
     *
     * @mbg.generated Wed Mar 22 20:50:33 CST 2017
     */
    public void setQosband(String qosband) {
        this.qosband = qosband;
    }
}