package main.java.com.tanklab.entity;

public class Qos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.belong_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String belongSwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.qos_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String qosId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.qos_uuid
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String qosUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.max_rate
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String maxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qos.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.id
     *
     * @return the value of qos.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.id
     *
     * @param id the value for qos.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.belong_sw_id
     *
     * @return the value of qos.belong_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getBelongSwId() {
        return belongSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.belong_sw_id
     *
     * @param belongSwId the value for qos.belong_sw_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setBelongSwId(String belongSwId) {
        this.belongSwId = belongSwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.qos_id
     *
     * @return the value of qos.qos_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getQosId() {
        return qosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.qos_id
     *
     * @param qosId the value for qos.qos_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setQosId(String qosId) {
        this.qosId = qosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.qos_uuid
     *
     * @return the value of qos.qos_uuid
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getQosUuid() {
        return qosUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.qos_uuid
     *
     * @param qosUuid the value for qos.qos_uuid
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setQosUuid(String qosUuid) {
        this.qosUuid = qosUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.max_rate
     *
     * @return the value of qos.max_rate
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getMaxRate() {
        return maxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.max_rate
     *
     * @param maxRate the value for qos.max_rate
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setMaxRate(String maxRate) {
        this.maxRate = maxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qos.type
     *
     * @return the value of qos.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qos.type
     *
     * @param type the value for qos.type
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }
}