package main.java.com.tanklab.entity;

public class Queue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue.id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue.queue_id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    private String queueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue.queue_uuid
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    private String queueUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue.qos_id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    private String qosId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue.max_rate
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    private Integer maxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue.min_rate
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    private Integer minRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue.external_id_key
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    private String externalIdKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue.external_id_value
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    private String externalIdValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue.id
     *
     * @return the value of queue.id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue.id
     *
     * @param id the value for queue.id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue.queue_id
     *
     * @return the value of queue.queue_id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public String getQueueId() {
        return queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue.queue_id
     *
     * @param queueId the value for queue.queue_id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public void setQueueId(String queueId) {
        this.queueId = queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue.queue_uuid
     *
     * @return the value of queue.queue_uuid
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public String getQueueUuid() {
        return queueUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue.queue_uuid
     *
     * @param queueUuid the value for queue.queue_uuid
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public void setQueueUuid(String queueUuid) {
        this.queueUuid = queueUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue.qos_id
     *
     * @return the value of queue.qos_id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public String getQosId() {
        return qosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue.qos_id
     *
     * @param qosId the value for queue.qos_id
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public void setQosId(String qosId) {
        this.qosId = qosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue.max_rate
     *
     * @return the value of queue.max_rate
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public Integer getMaxRate() {
        return maxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue.max_rate
     *
     * @param maxRate the value for queue.max_rate
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public void setMaxRate(Integer maxRate) {
        this.maxRate = maxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue.min_rate
     *
     * @return the value of queue.min_rate
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public Integer getMinRate() {
        return minRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue.min_rate
     *
     * @param minRate the value for queue.min_rate
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public void setMinRate(Integer minRate) {
        this.minRate = minRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue.external_id_key
     *
     * @return the value of queue.external_id_key
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public String getExternalIdKey() {
        return externalIdKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue.external_id_key
     *
     * @param externalIdKey the value for queue.external_id_key
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public void setExternalIdKey(String externalIdKey) {
        this.externalIdKey = externalIdKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue.external_id_value
     *
     * @return the value of queue.external_id_value
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public String getExternalIdValue() {
        return externalIdValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue.external_id_value
     *
     * @param externalIdValue the value for queue.external_id_value
     *
     * @mbg.generated Fri Mar 24 14:53:55 CST 2017
     */
    public void setExternalIdValue(String externalIdValue) {
        this.externalIdValue = externalIdValue;
    }
}