package main.java.com.tanklab.entity;

public class Topology {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topology.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topology.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String topologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topology.topology_owner
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    private String topologyOwner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topology.id
     *
     * @return the value of topology.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topology.id
     *
     * @param id the value for topology.id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topology.topology_id
     *
     * @return the value of topology.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTopologyId() {
        return topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topology.topology_id
     *
     * @param topologyId the value for topology.topology_id
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTopologyId(String topologyId) {
        this.topologyId = topologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topology.topology_owner
     *
     * @return the value of topology.topology_owner
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getTopologyOwner() {
        return topologyOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topology.topology_owner
     *
     * @param topologyOwner the value for topology.topology_owner
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setTopologyOwner(String topologyOwner) {
        this.topologyOwner = topologyOwner;
    }
}