package main.java.com.tanklab.entity;

import java.util.ArrayList;
import java.util.List;

public class TopologyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public TopologyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTopologyIdIsNull() {
            addCriterion("topology_id is null");
            return (Criteria) this;
        }

        public Criteria andTopologyIdIsNotNull() {
            addCriterion("topology_id is not null");
            return (Criteria) this;
        }

        public Criteria andTopologyIdEqualTo(String value) {
            addCriterion("topology_id =", value, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdNotEqualTo(String value) {
            addCriterion("topology_id <>", value, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdGreaterThan(String value) {
            addCriterion("topology_id >", value, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdGreaterThanOrEqualTo(String value) {
            addCriterion("topology_id >=", value, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdLessThan(String value) {
            addCriterion("topology_id <", value, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdLessThanOrEqualTo(String value) {
            addCriterion("topology_id <=", value, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdLike(String value) {
            addCriterion("topology_id like", value, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdNotLike(String value) {
            addCriterion("topology_id not like", value, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdIn(List<String> values) {
            addCriterion("topology_id in", values, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdNotIn(List<String> values) {
            addCriterion("topology_id not in", values, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdBetween(String value1, String value2) {
            addCriterion("topology_id between", value1, value2, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyIdNotBetween(String value1, String value2) {
            addCriterion("topology_id not between", value1, value2, "topologyId");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerIsNull() {
            addCriterion("topology_owner is null");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerIsNotNull() {
            addCriterion("topology_owner is not null");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerEqualTo(String value) {
            addCriterion("topology_owner =", value, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerNotEqualTo(String value) {
            addCriterion("topology_owner <>", value, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerGreaterThan(String value) {
            addCriterion("topology_owner >", value, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("topology_owner >=", value, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerLessThan(String value) {
            addCriterion("topology_owner <", value, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerLessThanOrEqualTo(String value) {
            addCriterion("topology_owner <=", value, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerLike(String value) {
            addCriterion("topology_owner like", value, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerNotLike(String value) {
            addCriterion("topology_owner not like", value, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerIn(List<String> values) {
            addCriterion("topology_owner in", values, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerNotIn(List<String> values) {
            addCriterion("topology_owner not in", values, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerBetween(String value1, String value2) {
            addCriterion("topology_owner between", value1, value2, "topologyOwner");
            return (Criteria) this;
        }

        public Criteria andTopologyOwnerNotBetween(String value1, String value2) {
            addCriterion("topology_owner not between", value1, value2, "topologyOwner");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topology
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 23 19:18:25 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topology
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}