package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.Flowtable;
import main.java.com.tanklab.entity.FlowtableExample;
import org.apache.ibatis.annotations.Param;

public interface FlowtableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    long countByExample(FlowtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    int deleteByExample(FlowtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    int insert(Flowtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    int insertSelective(Flowtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    List<Flowtable> selectByExample(FlowtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    Flowtable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") Flowtable record, @Param("example") FlowtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    int updateByExample(@Param("record") Flowtable record, @Param("example") FlowtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    int updateByPrimaryKeySelective(Flowtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowtable
     *
     * @mbg.generated Sun Mar 26 20:49:43 CST 2017
     */
    int updateByPrimaryKey(Flowtable record);
}