package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.Flowentity;
import main.java.com.tanklab.entity.FlowentityExample;
import org.apache.ibatis.annotations.Param;

public interface FlowentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    long countByExample(FlowentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int deleteByExample(FlowentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int insert(Flowentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int insertSelective(Flowentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    List<Flowentity> selectByExample(FlowentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    Flowentity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") Flowentity record, @Param("example") FlowentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByExample(@Param("record") Flowentity record, @Param("example") FlowentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByPrimaryKeySelective(Flowentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flowentity
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByPrimaryKey(Flowentity record);
}