package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.Node;
import main.java.com.tanklab.entity.NodeExample;
import org.apache.ibatis.annotations.Param;

public interface NodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    long countByExample(NodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    int deleteByExample(NodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    int insert(Node record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    int insertSelective(Node record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    List<Node> selectByExample(NodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    Node selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") Node record, @Param("example") NodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    int updateByExample(@Param("record") Node record, @Param("example") NodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    int updateByPrimaryKeySelective(Node record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node
     *
     * @mbg.generated Wed Mar 22 17:40:06 CST 2017
     */
    int updateByPrimaryKey(Node record);
}