package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.OpenflowNode;
import main.java.com.tanklab.entity.OpenflowNodeExample;
import org.apache.ibatis.annotations.Param;

public interface OpenflowNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    long countByExample(OpenflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int deleteByExample(OpenflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int insert(OpenflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int insertSelective(OpenflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    List<OpenflowNode> selectByExample(OpenflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    OpenflowNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") OpenflowNode record, @Param("example") OpenflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByExample(@Param("record") OpenflowNode record, @Param("example") OpenflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByPrimaryKeySelective(OpenflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_node
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByPrimaryKey(OpenflowNode record);
}