package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.OpenflowPoint;
import main.java.com.tanklab.entity.OpenflowPointExample;
import org.apache.ibatis.annotations.Param;

public interface OpenflowPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    long countByExample(OpenflowPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int deleteByExample(OpenflowPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int insert(OpenflowPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int insertSelective(OpenflowPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    List<OpenflowPoint> selectByExample(OpenflowPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    OpenflowPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") OpenflowPoint record, @Param("example") OpenflowPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByExample(@Param("record") OpenflowPoint record, @Param("example") OpenflowPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByPrimaryKeySelective(OpenflowPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openflow_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByPrimaryKey(OpenflowPoint record);
}