package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.OvsdbPoint;
import main.java.com.tanklab.entity.OvsdbPointExample;
import org.apache.ibatis.annotations.Param;

public interface OvsdbPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    long countByExample(OvsdbPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int deleteByExample(OvsdbPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int insert(OvsdbPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int insertSelective(OvsdbPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    List<OvsdbPoint> selectByExample(OvsdbPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    OvsdbPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") OvsdbPoint record, @Param("example") OvsdbPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByExample(@Param("record") OvsdbPoint record, @Param("example") OvsdbPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByPrimaryKeySelective(OvsdbPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_point
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByPrimaryKey(OvsdbPoint record);
}