package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.OvsdbNode;
import main.java.com.tanklab.entity.OvsdbNodeExample;
import org.apache.ibatis.annotations.Param;

public interface OvsdbNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    long countByExample(OvsdbNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int deleteByExample(OvsdbNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int insert(OvsdbNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int insertSelective(OvsdbNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    List<OvsdbNode> selectByExample(OvsdbNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    OvsdbNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") OvsdbNode record, @Param("example") OvsdbNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByExample(@Param("record") OvsdbNode record, @Param("example") OvsdbNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByPrimaryKeySelective(OvsdbNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ovsdb_node
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByPrimaryKey(OvsdbNode record);
}