package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.Queue;
import main.java.com.tanklab.entity.QueueExample;
import org.apache.ibatis.annotations.Param;

public interface QueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    long countByExample(QueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int deleteByExample(QueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int insert(Queue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int insertSelective(Queue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    List<Queue> selectByExample(QueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    Queue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") Queue record, @Param("example") QueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByExample(@Param("record") Queue record, @Param("example") QueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByPrimaryKeySelective(Queue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue
     *
     * @mbg.generated Thu Mar 23 19:18:25 CST 2017
     */
    int updateByPrimaryKey(Queue record);
}