package main.java.com.tanklab.mybatis.mapper;

import java.util.List;
import main.java.com.tanklab.entity.Topology;
import main.java.com.tanklab.entity.TopologyExample;
import org.apache.ibatis.annotations.Param;

public interface TopologyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    long countByExample(TopologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int deleteByExample(TopologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int insert(Topology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int insertSelective(Topology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    List<Topology> selectByExample(TopologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    Topology selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") Topology record, @Param("example") TopologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByExample(@Param("record") Topology record, @Param("example") TopologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByPrimaryKeySelective(Topology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topology
     *
     * @mbg.generated Sat Mar 25 11:02:41 CST 2017
     */
    int updateByPrimaryKey(Topology record);
}